//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrankChat.Mobile.Core.Presentation.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PrankChat.Mobile.Core.Presentation.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        public static string Home_Tab {
            get {
                return ResourceManager.GetString("Home_Tab", resourceCulture);
            }
        }
        
        public static string Rate_Tab {
            get {
                return ResourceManager.GetString("Rate_Tab", resourceCulture);
            }
        }
        
        public static string Orders_Tab {
            get {
                return ResourceManager.GetString("Orders_Tab", resourceCulture);
            }
        }
        
        public static string Profile_Tab {
            get {
                return ResourceManager.GetString("Profile_Tab", resourceCulture);
            }
        }
        
        public static string Popular_Publication_Tab {
            get {
                return ResourceManager.GetString("Popular_Publication_Tab", resourceCulture);
            }
        }
        
        public static string Actual_Publication_Tab {
            get {
                return ResourceManager.GetString("Actual_Publication_Tab", resourceCulture);
            }
        }
        
        public static string MyFeed_Publication_Tab {
            get {
                return ResourceManager.GetString("MyFeed_Publication_Tab", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Day {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Day", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Week {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Week", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Month {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Month", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Quarter {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Quarter", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_HalfYear {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_HalfYear", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Search_View_Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_View_Search_Placeholder", resourceCulture);
            }
        }
        
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string Error_Unexpected_Server {
            get {
                return ResourceManager.GetString("Error_Unexpected_Server", resourceCulture);
            }
        }
        
        public static string Error_Unexpected_Not_Found {
            get {
                return ResourceManager.GetString("Error_Unexpected_Not_Found", resourceCulture);
            }
        }
        
        public static string Error_Unexpected_Network {
            get {
                return ResourceManager.GetString("Error_Unexpected_Network", resourceCulture);
            }
        }
        
        public static string LoginView_Email_Placeholder {
            get {
                return ResourceManager.GetString("LoginView_Email_Placeholder", resourceCulture);
            }
        }
        
        public static string LoginView_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginView_Password_Placeholder", resourceCulture);
            }
        }
        
        public static string LoginView_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("LoginView_ForgotPassword_Title", resourceCulture);
            }
        }
        
        public static string LoginView_ForgotPassword_Button {
            get {
                return ResourceManager.GetString("LoginView_ForgotPassword_Button", resourceCulture);
            }
        }
        
        public static string LoginView_Continue_Button {
            get {
                return ResourceManager.GetString("LoginView_Continue_Button", resourceCulture);
            }
        }
        
        public static string LoginView_CreateAccount_Button {
            get {
                return ResourceManager.GetString("LoginView_CreateAccount_Button", resourceCulture);
            }
        }
        
        public static string LoginView_Login_Title {
            get {
                return ResourceManager.GetString("LoginView_Login_Title", resourceCulture);
            }
        }
        
        public static string LoginView_AltLogin_Title {
            get {
                return ResourceManager.GetString("LoginView_AltLogin_Title", resourceCulture);
            }
        }
        
        public static string RegistrationView_Title {
            get {
                return ResourceManager.GetString("RegistrationView_Title", resourceCulture);
            }
        }
        
        public static string RegistrationView_Email_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Email_Placeholder", resourceCulture);
            }
        }
        
        public static string RegistrationView_RegisteredYet_Label {
            get {
                return ResourceManager.GetString("RegistrationView_RegisteredYet_Label", resourceCulture);
            }
        }
        
        public static string RegistrationView_Login_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Login_Button", resourceCulture);
            }
        }
        
        public static string RegistrationView_Login_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Login_Placeholder", resourceCulture);
            }
        }
        
        public static string RegistrationView_Name_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Name_Placeholder", resourceCulture);
            }
        }
        
        public static string RegistrationView_Birthday_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Birthday_Placeholder", resourceCulture);
            }
        }
        
        public static string RegistrationView_Password_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Password_Placeholder", resourceCulture);
            }
        }
        
        public static string RegistrationView_PasswordRepeat_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_PasswordRepeat_Placeholder", resourceCulture);
            }
        }
        
        public static string RegistrationView_GenderSelect_Title {
            get {
                return ResourceManager.GetString("RegistrationView_GenderSelect_Title", resourceCulture);
            }
        }
        
        public static string RegistrationView_Male_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Male_Button", resourceCulture);
            }
        }
        
        public static string RegistrationView_Female_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Female_Button", resourceCulture);
            }
        }
        
        public static string RegistrationView_Register_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Register_Button", resourceCulture);
            }
        }
        
        public static string RegistrationView_StepTwo_Title {
            get {
                return ResourceManager.GetString("RegistrationView_StepTwo_Title", resourceCulture);
            }
        }
        
        public static string RegistrationView_StepThree_Title {
            get {
                return ResourceManager.GetString("RegistrationView_StepThree_Title", resourceCulture);
            }
        }
        
        public static string RegistrationView_Congrats_Title {
            get {
                return ResourceManager.GetString("RegistrationView_Congrats_Title", resourceCulture);
            }
        }
        
        public static string RegistrationView_Confirmation_Label {
            get {
                return ResourceManager.GetString("RegistrationView_Confirmation_Label", resourceCulture);
            }
        }
        
        public static string RegistrationView_GoToFeed_Button {
            get {
                return ResourceManager.GetString("RegistrationView_GoToFeed_Button", resourceCulture);
            }
        }
        
        public static string Password_Recovery_View_Title {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Title", resourceCulture);
            }
        }
        
        public static string Password_Recovery_View_Email_Placeholder {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Email_Placeholder", resourceCulture);
            }
        }
        
        public static string Password_Recovery_View_Recovery_Button {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Recovery_Button", resourceCulture);
            }
        }
        
        public static string Password_Recovery_View_Attention {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Attention", resourceCulture);
            }
        }
        
        public static string Password_Recovery_View_Finish_Text {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Finish_Text", resourceCulture);
            }
        }
        
        public static string ProfileView_Menu_Favourites {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Favourites", resourceCulture);
            }
        }
        
        public static string ProfileView_Menu_TaskSubscriptions {
            get {
                return ResourceManager.GetString("ProfileView_Menu_TaskSubscriptions", resourceCulture);
            }
        }
        
        public static string ProfileView_Menu_Faq {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Faq", resourceCulture);
            }
        }
        
        public static string ProfileView_Menu_Support {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Support", resourceCulture);
            }
        }
        
        public static string ProfileView_Menu_Settings {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Settings", resourceCulture);
            }
        }
        
        public static string ProfileView_Menu_LogOut {
            get {
                return ResourceManager.GetString("ProfileView_Menu_LogOut", resourceCulture);
            }
        }
        
        public static string ProfileView_Refill {
            get {
                return ResourceManager.GetString("ProfileView_Refill", resourceCulture);
            }
        }
        
        public static string ProfileView_Withdrawal {
            get {
                return ResourceManager.GetString("ProfileView_Withdrawal", resourceCulture);
            }
        }
        
        public static string ProfileView_Orders_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Orders_Subtitle", resourceCulture);
            }
        }
        
        public static string ProfileView_Completed_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Completed_Subtitle", resourceCulture);
            }
        }
        
        public static string ProfileView_Subscribers_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Subscribers_Subtitle", resourceCulture);
            }
        }
        
        public static string ProfileView_Subscriptions_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Subscriptions_Subtitle", resourceCulture);
            }
        }
        
        public static string ProfileView_MyOrders_Tab {
            get {
                return ResourceManager.GetString("ProfileView_MyOrders_Tab", resourceCulture);
            }
        }
        
        public static string ProfileView_CompletedOrders_Tab {
            get {
                return ResourceManager.GetString("ProfileView_CompletedOrders_Tab", resourceCulture);
            }
        }
        
        public static string Order_View_Time_Text {
            get {
                return ResourceManager.GetString("Order_View_Time_Text", resourceCulture);
            }
        }
        
        public static string Order_View_Price_Text {
            get {
                return ResourceManager.GetString("Order_View_Price_Text", resourceCulture);
            }
        }
        
        public static string Order_View_Day {
            get {
                return ResourceManager.GetString("Order_View_Day", resourceCulture);
            }
        }
        
        public static string Order_View_Hour {
            get {
                return ResourceManager.GetString("Order_View_Hour", resourceCulture);
            }
        }
        
        public static string Order_View_Minute {
            get {
                return ResourceManager.GetString("Order_View_Minute", resourceCulture);
            }
        }
        
        public static string Order_View_Details {
            get {
                return ResourceManager.GetString("Order_View_Details", resourceCulture);
            }
        }
        
        public static string Order_View_New_Task {
            get {
                return ResourceManager.GetString("Order_View_New_Task", resourceCulture);
            }
        }
        
        public static string Order_View_My_Task {
            get {
                return ResourceManager.GetString("Order_View_My_Task", resourceCulture);
            }
        }
        
        public static string OrdersView_Filter_AllTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_AllTasks", resourceCulture);
            }
        }
        
        public static string OrdersView_Filter_NewTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_NewTasks", resourceCulture);
            }
        }
        
        public static string OrdersView_Filter_CurrentTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_CurrentTasks", resourceCulture);
            }
        }
        
        public static string OrdersView_Filter_MyTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_MyTasks", resourceCulture);
            }
        }
        
        public static string RateView_Filter_AllTasks {
            get {
                return ResourceManager.GetString("RateView_Filter_AllTasks", resourceCulture);
            }
        }
        
        public static string RateView_Filter_MyTasks {
            get {
                return ResourceManager.GetString("RateView_Filter_MyTasks", resourceCulture);
            }
        }
        
        public static string RateView_Filter_NewTasks {
            get {
                return ResourceManager.GetString("RateView_Filter_NewTasks", resourceCulture);
            }
        }
        
        public static string RateView_Title_Label {
            get {
                return ResourceManager.GetString("RateView_Title_Label", resourceCulture);
            }
        }
        
        public static string OrdersView_Title_Label {
            get {
                return ResourceManager.GetString("OrdersView_Title_Label", resourceCulture);
            }
        }
    }
}
