//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrankChat.Mobile.Core.Presentation.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PrankChat.Mobile.Core.Presentation.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        public static string Home_Tab {
            get {
                return ResourceManager.GetString("Home_Tab", resourceCulture);
            }
        }
        
        public static string Rate_Tab {
            get {
                return ResourceManager.GetString("Rate_Tab", resourceCulture);
            }
        }
        
        public static string Orders_Tab {
            get {
                return ResourceManager.GetString("Orders_Tab", resourceCulture);
            }
        }
        
        public static string Profile_Tab {
            get {
                return ResourceManager.GetString("Profile_Tab", resourceCulture);
            }
        }
        
        public static string Popular_Publication_Tab {
            get {
                return ResourceManager.GetString("Popular_Publication_Tab", resourceCulture);
            }
        }
        
        public static string Actual_Publication_Tab {
            get {
                return ResourceManager.GetString("Actual_Publication_Tab", resourceCulture);
            }
        }
        
        public static string MyFeed_Publication_Tab {
            get {
                return ResourceManager.GetString("MyFeed_Publication_Tab", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Day {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Day", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Week {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Week", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Month {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Month", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_Quarter {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Quarter", resourceCulture);
            }
        }
        
        public static string Publication_Tab_Filter_HalfYear {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_HalfYear", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Search_View_Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_View_Search_Placeholder", resourceCulture);
            }
        }
        
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
    }
}
