//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrankChat.Mobile.Core.Presentation.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrankChat.Mobile.Core.Presentation.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Актуальное.
        /// </summary>
        public static string Actual_Publication_Tab {
            get {
                return ResourceManager.GetString("Actual_Publication_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prank Chat.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить.
        /// </summary>
        public static string CashboxView_Fillup_Button {
            get {
                return ResourceManager.GetString("CashboxView_Fillup_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнение.
        /// </summary>
        public static string CashboxView_Fillup_Tab {
            get {
                return ResourceManager.GetString("CashboxView_Fillup_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите метод для пополнения:.
        /// </summary>
        public static string CashboxView_FillupMethodSelect_Title {
            get {
                return ResourceManager.GetString("CashboxView_FillupMethodSelect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 000 000 ₽.
        /// </summary>
        public static string CashboxView_Price_Placeholder {
            get {
                return ResourceManager.GetString("CashboxView_Price_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Касса.
        /// </summary>
        public static string CashboxView_Title {
            get {
                return ResourceManager.GetString("CashboxView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снять.
        /// </summary>
        public static string CashboxView_Withdrawal_Button {
            get {
                return ResourceManager.GetString("CashboxView_Withdrawal_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Снятие.
        /// </summary>
        public static string CashboxView_Withdrawal_Tab {
            get {
                return ResourceManager.GetString("CashboxView_Withdrawal_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно для снятия:.
        /// </summary>
        public static string CashboxView_WithdrawalAvailable_Title {
            get {
                return ResourceManager.GetString("CashboxView_WithdrawalAvailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите метод для снятия:.
        /// </summary>
        public static string CashboxView_WithdrawalMethodSelect_Title {
            get {
                return ResourceManager.GetString("CashboxView_WithdrawalMethodSelect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e9e6beb9c4284289ac68b9ab76a9ee56.
        /// </summary>
        public static string com_crashlytics_android_build_id {
            get {
                return ResourceManager.GetString("com.crashlytics.android.build_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7343996.
        /// </summary>
        public static string com_vk_sdk_AppId {
            get {
                return ResourceManager.GetString("com_vk_sdk_AppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string CommentView_Title {
            get {
                return ResourceManager.GetString("CommentView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить видео.
        /// </summary>
        public static string Competition_Load_Video {
            get {
                return ResourceManager.GetString("Competition_Load_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призовой фонд.
        /// </summary>
        public static string Competition_Prize_Pool {
            get {
                return ResourceManager.GetString("Competition_Prize_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учасник.
        /// </summary>
        public static string Competition_Prize_Pool_Participant {
            get {
                return ResourceManager.GetString("Competition_Prize_Pool_Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг.
        /// </summary>
        public static string Competition_Prize_Pool_Rating {
            get {
                return ResourceManager.GetString("Competition_Prize_Pool_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты.
        /// </summary>
        public static string Competition_Results {
            get {
                return ResourceManager.GetString("Competition_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правила конкурса.
        /// </summary>
        public static string Competition_Rules {
            get {
                return ResourceManager.GetString("Competition_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итоги.
        /// </summary>
        public static string Competitions_Finished {
            get {
                return ResourceManager.GetString("Competitions_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период проведения конкурса:.
        /// </summary>
        public static string Competitions_Finished_Term {
            get {
                return ResourceManager.GetString("Competitions_Finished_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string Competitions_More {
            get {
                return ResourceManager.GetString("Competitions_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        public static string Competitions_New {
            get {
                return ResourceManager.GetString("Competitions_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До начала голосования:.
        /// </summary>
        public static string Competitions_New_Term {
            get {
                return ResourceManager.GetString("Competitions_New_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять участие.
        /// </summary>
        public static string Competitions_Participate {
            get {
                return ResourceManager.GetString("Competitions_Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призовой фонд турнира:.
        /// </summary>
        public static string Competitions_Prize_Pool {
            get {
                return ResourceManager.GetString("Competitions_Prize_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смотреть.
        /// </summary>
        public static string Competitions_See {
            get {
                return ResourceManager.GetString("Competitions_See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конкурсы.
        /// </summary>
        public static string Competitions_Tab {
            get {
                return ResourceManager.GetString("Competitions_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосование.
        /// </summary>
        public static string Competitions_Voting {
            get {
                return ResourceManager.GetString("Competitions_Voting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to До конца голосования:.
        /// </summary>
        public static string Competitions_Voting_Term {
            get {
                return ResourceManager.GetString("Competitions_Voting_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место.
        /// </summary>
        public static string Competiton_Prize_Pool_Place {
            get {
                return ResourceManager.GetString("Competiton_Prize_Pool_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено модератору.
        /// </summary>
        public static string ComplainSuccessful {
            get {
                return ResourceManager.GetString("ComplainSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мошенничество или обман.
        /// </summary>
        public static string Complaint_Cheating {
            get {
                return ResourceManager.GetString("Complaint_Cheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо, что сообщили нам об этом.
        /// </summary>
        public static string Complaint_Complete_Message {
            get {
                return ResourceManager.GetString("Complaint_Complete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Насилие или опасные организации.
        /// </summary>
        public static string Complaint_Dangerous_Organizations {
            get {
                return ResourceManager.GetString("Complaint_Dangerous_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оскорбления или травля.
        /// </summary>
        public static string Complaint_Hostile_Utterances {
            get {
                return ResourceManager.GetString("Complaint_Hostile_Utterances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порнография и нагота.
        /// </summary>
        public static string Complaint_Naked_Content {
            get {
                return ResourceManager.GetString("Complaint_Naked_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прочее.
        /// </summary>
        public static string Complaint_Other {
            get {
                return ResourceManager.GetString("Complaint_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нарушение авторских прав.
        /// </summary>
        public static string Complaint_Rights_Violation {
            get {
                return ResourceManager.GetString("Complaint_Rights_Violation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это спам.
        /// </summary>
        public static string Complaint_Spam {
            get {
                return ResourceManager.GetString("Complaint_Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неприемлемый контент.
        /// </summary>
        public static string Complaint_Unacceptable_Content {
            get {
                return ResourceManager.GetString("Complaint_Unacceptable_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неприемлемая информация в профиле.
        /// </summary>
        public static string Complaint_Unacceptable_Information_In_Profile {
            get {
                return ResourceManager.GetString("Complaint_Unacceptable_Information_In_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использует чужое имя.
        /// </summary>
        public static string Complaint_Wrong_Name {
            get {
                return ResourceManager.GetString("Complaint_Wrong_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дней.
        /// </summary>
        public static string Count_Days {
            get {
                return ResourceManager.GetString("Count_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часов.
        /// </summary>
        public static string Count_Hours {
            get {
                return ResourceManager.GetString("Count_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Count_Millions {
            get {
                return ResourceManager.GetString("Count_Millions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минут.
        /// </summary>
        public static string Count_Minutes {
            get {
                return ResourceManager.GetString("Count_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просмотра.
        /// </summary>
        public static string Count_Of_Viewing {
            get {
                return ResourceManager.GetString("Count_Of_Viewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        public static string Count_Thousand {
            get {
                return ResourceManager.GetString("Count_Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просмотр.
        /// </summary>
        public static string Count_View {
            get {
                return ResourceManager.GetString("Count_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to просмотров.
        /// </summary>
        public static string Count_Views {
            get {
                return ResourceManager.GetString("Count_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите период действия заказа..
        /// </summary>
        public static string CreateOrderView_Choose_Time_Period {
            get {
                return ResourceManager.GetString("CreateOrderView_Choose_Time_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата исполнения.
        /// </summary>
        public static string CreateOrderView_CompleteDate_Placeholder {
            get {
                return ResourceManager.GetString("CreateOrderView_CompleteDate_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать заказ.
        /// </summary>
        public static string CreateOrderView_Create_Button {
            get {
                return ResourceManager.GetString("CreateOrderView_Create_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание заказа.
        /// </summary>
        public static string CreateOrderView_Description_Placeholder {
            get {
                return ResourceManager.GetString("CreateOrderView_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть исполнителя.
        /// </summary>
        public static string CreateOrderView_HideExecutor_Button {
            get {
                return ResourceManager.GetString("CreateOrderView_HideExecutor_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название заказа.
        /// </summary>
        public static string CreateOrderView_Name_Placeholder {
            get {
                return ResourceManager.GetString("CreateOrderView_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 000 ₽.
        /// </summary>
        public static string CreateOrderView_Price_Placeholder {
            get {
                return ResourceManager.GetString("CreateOrderView_Price_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string CreateOrderView_PriceTitle_Placeholder {
            get {
                return ResourceManager.GetString("CreateOrderView_PriceTitle_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание заказа.
        /// </summary>
        public static string CreateOrderView_Title {
            get {
                return ResourceManager.GetString("CreateOrderView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ₽.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to д..
        /// </summary>
        public static string Days_Short {
            get {
                return ResourceManager.GetString("Days_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Демо.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла неожиданная сетевая ошибка, пожалуйста, попробуйте снова..
        /// </summary>
        public static string Error_Unexpected_Network {
            get {
                return ResourceManager.GetString("Error_Unexpected_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось получить запрошенные данные..
        /// </summary>
        public static string Error_Unexpected_Not_Found {
            get {
                return ResourceManager.GetString("Error_Unexpected_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла непредвиденная ошибка на сервере. Мы уже получили информацию об этом и работаем над устранением проблемы..
        /// </summary>
        public static string Error_Unexpected_Server {
            get {
                return ResourceManager.GetString("Error_Unexpected_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в ленту.
        /// </summary>
        public static string FinishPasswordRecoveryView_GoToFeed_Button {
            get {
                return ResourceManager.GetString("FinishPasswordRecoveryView_GoToFeed_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в аккаунт.
        /// </summary>
        public static string FinishPasswordRecoveryView_GoToLogin_Button {
            get {
                return ResourceManager.GetString("FinishPasswordRecoveryView_GoToLogin_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home_Tab {
            get {
                return ResourceManager.GetString("Home_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч..
        /// </summary>
        public static string Hours_Short {
            get {
                return ResourceManager.GetString("Hours_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка скопирована.
        /// </summary>
        public static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти без регистрации.
        /// </summary>
        public static string Login_Without_Registration {
            get {
                return ResourceManager.GetString("Login_Without_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти через:.
        /// </summary>
        public static string LoginView_AltLogin_Title {
            get {
                return ResourceManager.GetString("LoginView_AltLogin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжить.
        /// </summary>
        public static string LoginView_Continue_Button {
            get {
                return ResourceManager.GetString("LoginView_Continue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет аккаунта? Создать новый.
        /// </summary>
        public static string LoginView_CreateAccount_Button {
            get {
                return ResourceManager.GetString("LoginView_CreateAccount_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email.
        /// </summary>
        public static string LoginView_Email_Placeholder {
            get {
                return ResourceManager.GetString("LoginView_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Востановить.
        /// </summary>
        public static string LoginView_ForgotPassword_Button {
            get {
                return ResourceManager.GetString("LoginView_ForgotPassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Востановление пароля.
        /// </summary>
        public static string LoginView_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("LoginView_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LoginView_Login_Title {
            get {
                return ResourceManager.GetString("LoginView_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string LoginView_Password_Placeholder {
            get {
                return ResourceManager.GetString("LoginView_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мин..
        /// </summary>
        public static string Minutes_Short {
            get {
                return ResourceManager.GetString("Minutes_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моя лента.
        /// </summary>
        public static string MyFeed_Publication_Tab {
            get {
                return ResourceManager.GetString("MyFeed_Publication_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Непросмотрено.
        /// </summary>
        public static string NotificationStatus_NotViewed {
            get {
                return ResourceManager.GetString("NotificationStatus_NotViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотрено.
        /// </summary>
        public static string NotificationStatus_Viewed {
            get {
                return ResourceManager.GetString("NotificationStatus_Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомления.
        /// </summary>
        public static string NotificationView_Title {
            get {
                return ResourceManager.GetString("NotificationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикуй свое видео и стань известным.
        /// </summary>
        public static string OnBoarding_Fifth_Description {
            get {
                return ResourceManager.GetString("OnBoarding_Fifth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Делай смешно !!!.
        /// </summary>
        public static string OnBoarding_Fifth_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Fifth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ленте каждый автор PrankChat публикует свое эксклюзивное видео которого еще нет ни где. Просматривай и наслаждайся.
        /// </summary>
        public static string OnBoarding_First_Description {
            get {
                return ResourceManager.GetString("OnBoarding_First_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смотри смешные видео.
        /// </summary>
        public static string OnBoarding_First_Title {
            get {
                return ResourceManager.GetString("OnBoarding_First_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrankChat регулярно проводит конкурсы на лучшее видео с денежными призами. Участие бесплатное.
        /// </summary>
        public static string OnBoarding_Fourth_Description {
            get {
                return ResourceManager.GetString("OnBoarding_Fourth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to участвуй в конкурсах.
        /// </summary>
        public static string OnBoarding_Fourth_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Fourth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в ленту.
        /// </summary>
        public static string OnBoarding_Go_To_Main {
            get {
                return ResourceManager.GetString("OnBoarding_Go_To_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напиши любой заказ и пользователи PrankChat его экранизируют. Публикуй видео и становись знаменитым.
        /// </summary>
        public static string OnBoarding_Second_Description {
            get {
                return ResourceManager.GetString("OnBoarding_Second_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создавай свой заказ и получай видео.
        /// </summary>
        public static string OnBoarding_Second_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Second_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи PrankChat публикуют заказы по которым ты можешь снять свое видео и получить оплату.
        /// </summary>
        public static string OnBoarding_Third_Description {
            get {
                return ResourceManager.GetString("OnBoarding_Third_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняй заказы и получай деньги.
        /// </summary>
        public static string OnBoarding_Third_Title {
            get {
                return ResourceManager.GetString("OnBoarding_Third_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string Order_Add {
            get {
                return ResourceManager.GetString("Order_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите создать заказ? .
        /// </summary>
        public static string Order_Create_Message {
            get {
                return ResourceManager.GetString("Order_Create_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День.
        /// </summary>
        public static string Order_View_Day {
            get {
                return ResourceManager.GetString("Order_View_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        public static string Order_View_Details {
            get {
                return ResourceManager.GetString("Order_View_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Часа.
        /// </summary>
        public static string Order_View_Hour {
            get {
                return ResourceManager.GetString("Order_View_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минут.
        /// </summary>
        public static string Order_View_Minute {
            get {
                return ResourceManager.GetString("Order_View_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои заказы.
        /// </summary>
        public static string Order_View_My_Task {
            get {
                return ResourceManager.GetString("Order_View_My_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый заказ.
        /// </summary>
        public static string Order_View_New_Task {
            get {
                return ResourceManager.GetString("Order_View_New_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма зкакза:.
        /// </summary>
        public static string Order_View_Price_Text {
            get {
                return ResourceManager.GetString("Order_View_Price_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время заказа:.
        /// </summary>
        public static string Order_View_Time_Text {
            get {
                return ResourceManager.GetString("Order_View_Time_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите отменить заказ?.
        /// </summary>
        public static string OrderDetails_View_Cancel_Title {
            get {
                return ResourceManager.GetString("OrderDetails_View_Cancel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        public static string OrderDetailsView_Accept_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Accept_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В спор.
        /// </summary>
        public static string OrderDetailsView_Argue_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Argue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string OrderDetailsView_Cancel_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соответствует видео заказу?.
        /// </summary>
        public static string OrderDetailsView_Corresponds_To_Video_Text {
            get {
                return ResourceManager.GetString("OrderDetailsView_Corresponds_To_Video_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить видео:.
        /// </summary>
        public static string OrderDetailsView_Download_Text {
            get {
                return ResourceManager.GetString("OrderDetailsView_Download_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнить.
        /// </summary>
        public static string OrderDetailsView_Execute_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Execute_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить видео.
        /// </summary>
        public static string OrderDetailsView_LoadVideo {
            get {
                return ResourceManager.GetString("OrderDetailsView_LoadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string OrderDetailsView_No_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_No_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма заказа:.
        /// </summary>
        public static string OrderDetailsView_Price_Text {
            get {
                return ResourceManager.GetString("OrderDetailsView_Price_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписаться.
        /// </summary>
        public static string OrderDetailsView_Subscribe_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Subscribe_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взять заказ.
        /// </summary>
        public static string OrderDetailsView_Take_Order_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Take_Order_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите стать исполнителем данного заказа?.
        /// </summary>
        public static string OrderDetailsView_TakeOrderQuestion {
            get {
                return ResourceManager.GetString("OrderDetailsView_TakeOrderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Взять заказ.
        /// </summary>
        public static string OrderDetailsView_TakeOrderTitle {
            get {
                return ResourceManager.GetString("OrderDetailsView_TakeOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время заказа:.
        /// </summary>
        public static string OrderDetailsView_Time_Text {
            get {
                return ResourceManager.GetString("OrderDetailsView_Time_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ.
        /// </summary>
        public static string OrderDetailsView_Title {
            get {
                return ResourceManager.GetString("OrderDetailsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнитель:.
        /// </summary>
        public static string OrderDetailsView_Took_The_Order_Text {
            get {
                return ResourceManager.GetString("OrderDetailsView_Took_The_Order_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отписаться.
        /// </summary>
        public static string OrderDetailsView_Unsubscribe_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Unsubscribe_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видео отправлено, после обработки у заказчика будет 24 часа на принятие или отправки в спор..
        /// </summary>
        public static string OrderDetailsView_Video_Uploaded {
            get {
                return ResourceManager.GetString("OrderDetailsView_Video_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string OrderDetailsView_Yes_Button {
            get {
                return ResourceManager.GetString("OrderDetailsView_Yes_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В споре.
        /// </summary>
        public static string Orders_In_Dispute {
            get {
                return ResourceManager.GetString("Orders_In_Dispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string Orders_Tab {
            get {
                return ResourceManager.GetString("Orders_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string OrderStatus_Active {
            get {
                return ResourceManager.GetString("OrderStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменен.
        /// </summary>
        public static string OrderStatus_Cancelled {
            get {
                return ResourceManager.GetString("OrderStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыт после спора в пользу заказчика.
        /// </summary>
        public static string OrderStatus_ClosedAfterArbitrationCustomerWin {
            get {
                return ResourceManager.GetString("OrderStatus_ClosedAfterArbitrationCustomerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыт после спора в пользу исполнителя.
        /// </summary>
        public static string OrderStatus_ClosedAfterArbitrationExecutorWin {
            get {
                return ResourceManager.GetString("OrderStatus_ClosedAfterArbitrationExecutorWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполненный.
        /// </summary>
        public static string OrderStatus_Finished {
            get {
                return ResourceManager.GetString("OrderStatus_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В споре.
        /// </summary>
        public static string OrderStatus_InArbitration {
            get {
                return ResourceManager.GetString("OrderStatus_InArbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В работе.
        /// </summary>
        public static string OrderStatus_InWork {
            get {
                return ResourceManager.GetString("OrderStatus_InWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мое.
        /// </summary>
        public static string OrderStatus_MyOrder {
            get {
                return ResourceManager.GetString("OrderStatus_MyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На модерации.
        /// </summary>
        public static string OrderStatus_New {
            get {
                return ResourceManager.GetString("OrderStatus_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрытие спора.
        /// </summary>
        public static string OrderStatus_ProcessCloseArbitration {
            get {
                return ResourceManager.GetString("OrderStatus_ProcessCloseArbitration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменен модератором.
        /// </summary>
        public static string OrderStatus_Rejected {
            get {
                return ResourceManager.GetString("OrderStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ожидании.
        /// </summary>
        public static string OrderStatus_WaitFinish {
            get {
                return ResourceManager.GetString("OrderStatus_WaitFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все заказы.
        /// </summary>
        public static string OrdersView_Filter_AllTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_AllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказ в исполнении.
        /// </summary>
        public static string OrdersView_Filter_CurrentTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_CurrentTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои заказы.
        /// </summary>
        public static string OrdersView_Filter_MyTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые заказы.
        /// </summary>
        public static string OrdersView_Filter_NewTasks {
            get {
                return ResourceManager.GetString("OrdersView_Filter_NewTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string OrdersView_Title_Label {
            get {
                return ResourceManager.GetString("OrdersView_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание!.
        /// </summary>
        public static string Password_Recovery_View_Attention {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email.
        /// </summary>
        public static string Password_Recovery_View_Email_Placeholder {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На почту отправлено письмо с ссылкой для восстановления пароля..
        /// </summary>
        public static string Password_Recovery_View_Finish_Text {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Finish_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить.
        /// </summary>
        public static string Password_Recovery_View_Recovery_Button {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Recovery_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string Password_Recovery_View_Title {
            get {
                return ResourceManager.GetString("Password_Recovery_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать из галереи.
        /// </summary>
        public static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярное.
        /// </summary>
        public static string Popular_Publication_Tab {
            get {
                return ResourceManager.GetString("Popular_Publication_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка видео.
        /// </summary>
        public static string Processing_Video {
            get {
                return ResourceManager.GetString("Processing_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На Вашу почту отправлено письмо с подтверждением.
        /// </summary>
        public static string Profile_Email_Confirmation_Sent {
            get {
                return ResourceManager.GetString("Profile_Email_Confirmation_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить повторно.
        /// </summary>
        public static string Profile_Resend_Confirmation {
            get {
                return ResourceManager.GetString("Profile_Resend_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile_Tab {
            get {
                return ResourceManager.GetString("Profile_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша почта не подтверждена.
        /// </summary>
        public static string Profile_Your_Email_Not_Actual {
            get {
                return ResourceManager.GetString("Profile_Your_Email_Not_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string ProfileUpdateView_Birthday_Placeholder {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Birthday_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string ProfileUpdateView_Button_Save {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пароль.
        /// </summary>
        public static string ProfileUpdateView_ChangePassword {
            get {
                return ResourceManager.GetString("ProfileUpdateView_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О себе.
        /// </summary>
        public static string ProfileUpdateView_Description_Placeholder {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ProfileUpdateView_Email_Placeholder {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пол.
        /// </summary>
        public static string ProfileUpdateView_GenderSelect_Title {
            get {
                return ResourceManager.GetString("ProfileUpdateView_GenderSelect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string ProfileUpdateView_Login_Placeholder {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Login_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string ProfileUpdateView_Name_Placeholder {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить фото профиля.
        /// </summary>
        public static string ProfileUpdateView_PhotoChange_Title {
            get {
                return ResourceManager.GetString("ProfileUpdateView_PhotoChange_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить профиль.
        /// </summary>
        public static string ProfileUpdateView_Title {
            get {
                return ResourceManager.GetString("ProfileUpdateView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выполнено.
        /// </summary>
        public static string ProfileView_Completed_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Completed_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я исполняю.
        /// </summary>
        public static string ProfileView_CompletedOrders_Tab {
            get {
                return ResourceManager.GetString("ProfileView_CompletedOrders_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string ProfileView_Menu_Faq {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Избранные видео.
        /// </summary>
        public static string ProfileView_Menu_Favourites {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из аккаунта.
        /// </summary>
        public static string ProfileView_Menu_LogOut {
            get {
                return ResourceManager.GetString("ProfileView_Menu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        public static string ProfileView_Menu_Settings {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справки/отзывы.
        /// </summary>
        public static string ProfileView_Menu_Support {
            get {
                return ResourceManager.GetString("ProfileView_Menu_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписки на заказ.
        /// </summary>
        public static string ProfileView_Menu_TaskSubscriptions {
            get {
                return ResourceManager.GetString("ProfileView_Menu_TaskSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я заказал.
        /// </summary>
        public static string ProfileView_MyOrders_Tab {
            get {
                return ResourceManager.GetString("ProfileView_MyOrders_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to заказов.
        /// </summary>
        public static string ProfileView_Orders_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Orders_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пополнить.
        /// </summary>
        public static string ProfileView_Refill {
            get {
                return ResourceManager.GetString("ProfileView_Refill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подписчики.
        /// </summary>
        public static string ProfileView_Subscribers_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Subscribers_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подписки.
        /// </summary>
        public static string ProfileView_Subscriptions_Subtitle {
            get {
                return ResourceManager.GetString("ProfileView_Subscriptions_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вывести.
        /// </summary>
        public static string ProfileView_Withdrawal {
            get {
                return ResourceManager.GetString("ProfileView_Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожаловаться....
        /// </summary>
        public static string Publication_Item_Complain {
            get {
                return ResourceManager.GetString("Publication_Item_Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать ссылку.
        /// </summary>
        public static string Publication_Item_Copy_Link {
            get {
                return ResourceManager.GetString("Publication_Item_Copy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подписаться на автора.
        /// </summary>
        public static string Publication_Item_Subscribe_To_Author {
            get {
                return ResourceManager.GetString("Publication_Item_Subscribe_To_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За день.
        /// </summary>
        public static string Publication_Tab_Filter_Day {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За полгода.
        /// </summary>
        public static string Publication_Tab_Filter_HalfYear {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_HalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За месяц.
        /// </summary>
        public static string Publication_Tab_Filter_Month {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За квартал.
        /// </summary>
        public static string Publication_Tab_Filter_Quarter {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За неделю.
        /// </summary>
        public static string Publication_Tab_Filter_Week {
            get {
                return ResourceManager.GetString("Publication_Tab_Filter_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка.
        /// </summary>
        public static string Rate_Tab {
            get {
                return ResourceManager.GetString("Rate_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все заказы в споре.
        /// </summary>
        public static string RateView_Filter_AllTasks {
            get {
                return ResourceManager.GetString("RateView_Filter_AllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои заказы в споре.
        /// </summary>
        public static string RateView_Filter_MyTasks {
            get {
                return ResourceManager.GetString("RateView_Filter_MyTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые заказы в споре.
        /// </summary>
        public static string RateView_Filter_NewTasks {
            get {
                return ResourceManager.GetString("RateView_Filter_NewTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка.
        /// </summary>
        public static string RateView_Title_Label {
            get {
                return ResourceManager.GetString("RateView_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценить.
        /// </summary>
        public static string RateView_Vote_Button {
            get {
                return ResourceManager.GetString("RateView_Vote_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string RegistrationView_Birthday_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Birthday_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На почту отправлено письмо с верификацией email адреса. Для завершения регистрации, пожалуйста подтвердите Ваш email.
        /// </summary>
        public static string RegistrationView_Confirmation_Label {
            get {
                return ResourceManager.GetString("RegistrationView_Confirmation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поздравлем!.
        /// </summary>
        public static string RegistrationView_Congrats_Title {
            get {
                return ResourceManager.GetString("RegistrationView_Congrats_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите email.
        /// </summary>
        public static string RegistrationView_Email_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to жен.
        /// </summary>
        public static string RegistrationView_Female_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Female_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пол:.
        /// </summary>
        public static string RegistrationView_GenderSelect_Title {
            get {
                return ResourceManager.GetString("RegistrationView_GenderSelect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти в ленту.
        /// </summary>
        public static string RegistrationView_GoToFeed_Button {
            get {
                return ResourceManager.GetString("RegistrationView_GoToFeed_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти в аккаунт.
        /// </summary>
        public static string RegistrationView_Login_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите логин.
        /// </summary>
        public static string RegistrationView_Login_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Login_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to муж.
        /// </summary>
        public static string RegistrationView_Male_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Male_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите имя.
        /// </summary>
        public static string RegistrationView_Name_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        public static string RegistrationView_Password_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string RegistrationView_PasswordRepeat_Placeholder {
            get {
                return ResourceManager.GetString("RegistrationView_PasswordRepeat_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string RegistrationView_Register_Button {
            get {
                return ResourceManager.GetString("RegistrationView_Register_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже зарегистрированы?.
        /// </summary>
        public static string RegistrationView_RegisteredYet_Label {
            get {
                return ResourceManager.GetString("RegistrationView_RegisteredYet_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг 3.
        /// </summary>
        public static string RegistrationView_StepThree_Title {
            get {
                return ResourceManager.GetString("RegistrationView_StepThree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаг 2.
        /// </summary>
        public static string RegistrationView_StepTwo_Title {
            get {
                return ResourceManager.GetString("RegistrationView_StepTwo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegistrationView_Title {
            get {
                return ResourceManager.GetString("RegistrationView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search_View_Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_View_Search_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сек..
        /// </summary>
        public static string Seconds_Short {
            get {
                return ResourceManager.GetString("Seconds_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коп. ссылку.
        /// </summary>
        public static string ShareDialog_CopyLink_Label {
            get {
                return ResourceManager.GetString("ShareDialog_CopyLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться ссылкой.
        /// </summary>
        public static string ShareDialog_LinkShareTitle {
            get {
                return ResourceManager.GetString("ShareDialog_LinkShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В Instagram.
        /// </summary>
        public static string ShareDialog_ShareInstagram_Label {
            get {
                return ResourceManager.GetString("ShareDialog_ShareInstagram_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string ShareDialog_Title {
            get {
                return ResourceManager.GetString("ShareDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cфотографировать.
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть равно {1}..
        /// </summary>
        public static string Validation_Error_CanNotMatch {
            get {
                return ResourceManager.GetString("Validation_Error_CanNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть пустым..
        /// </summary>
        public static string Validation_Error_Empty {
            get {
                return ResourceManager.GetString("Validation_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть больше чем {1}..
        /// </summary>
        public static string Validation_Error_GreaterThanRequired {
            get {
                return ResourceManager.GetString("Validation_Error_GreaterThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} имеет неверный формат..
        /// </summary>
        public static string Validation_Error_Invalid {
            get {
                return ResourceManager.GetString("Validation_Error_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не может быть меньше чем {1}..
        /// </summary>
        public static string Validation_Error_LowerThanRequired {
            get {
                return ResourceManager.GetString("Validation_Error_LowerThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не совпадает с {1}..
        /// </summary>
        public static string Validation_Error_NotMatch {
            get {
                return ResourceManager.GetString("Validation_Error_NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День рождения.
        /// </summary>
        public static string Validation_Field_Birthday {
            get {
                return ResourceManager.GetString("Validation_Field_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        public static string Validation_Field_Cost {
            get {
                return ResourceManager.GetString("Validation_Field_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Validation_Field_Description {
            get {
                return ResourceManager.GetString("Validation_Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Validation_Field_Email {
            get {
                return ResourceManager.GetString("Validation_Field_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Validation_Field_Gender {
            get {
                return ResourceManager.GetString("Validation_Field_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        public static string Validation_Field_Login {
            get {
                return ResourceManager.GetString("Validation_Field_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Validation_Field_Name {
            get {
                return ResourceManager.GetString("Validation_Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        public static string Validation_Field_OrderPeriod {
            get {
                return ResourceManager.GetString("Validation_Field_OrderPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Validation_Field_Password {
            get {
                return ResourceManager.GetString("Validation_Field_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повтор пароля.
        /// </summary>
        public static string Validation_Field_PasswordRepeat {
            get {
                return ResourceManager.GetString("Validation_Field_PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Validation_Field_Price {
            get {
                return ResourceManager.GetString("Validation_Field_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Validation_Field_Title {
            get {
                return ResourceManager.GetString("Validation_Field_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нед..
        /// </summary>
        public static string Weeks_Short {
            get {
                return ResourceManager.GetString("Weeks_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикрепить файл.
        /// </summary>
        public static string WithdrawalView_Attach_File {
            get {
                return ResourceManager.GetString("WithdrawalView_Attach_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикрепить файл.
        /// </summary>
        public static string WithdrawalView_AttachFile_Button {
            get {
                return ResourceManager.GetString("WithdrawalView_AttachFile_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удается отменить транзакцию для вывода средств.
        /// </summary>
        public static string WithdrawalView_Cancel_Withdrawal_Error {
            get {
                return ResourceManager.GetString("WithdrawalView_Cancel_Withdrawal_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string WithdrawalView_Card_Number {
            get {
                return ResourceManager.GetString("WithdrawalView_Card_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер карты.
        /// </summary>
        public static string WithdrawalView_CardNumber_Placeholder {
            get {
                return ResourceManager.GetString("WithdrawalView_CardNumber_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма.
        /// </summary>
        public static string WithdrawalView_Cost {
            get {
                return ResourceManager.GetString("WithdrawalView_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string WithdrawalView_Create_Date {
            get {
                return ResourceManager.GetString("WithdrawalView_Create_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить данную карту?.
        /// </summary>
        public static string WithdrawalView_Delete_Card_Question {
            get {
                return ResourceManager.GetString("WithdrawalView_Delete_Card_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить карту.
        /// </summary>
        public static string WithdrawalView_Delete_Card_Text {
            get {
                return ResourceManager.GetString("WithdrawalView_Delete_Card_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карта не может быть пустой..
        /// </summary>
        public static string WithdrawalView_Empty_Card_Error {
            get {
                return ResourceManager.GetString("WithdrawalView_Empty_Card_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string WithdrawalView_FirstName_Placeholder {
            get {
                return ResourceManager.GetString("WithdrawalView_FirstName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string WithdrawalView_LastName_Placeholder {
            get {
                return ResourceManager.GetString("WithdrawalView_LastName_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string WithdrawalView_Name {
            get {
                return ResourceManager.GetString("WithdrawalView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В ожидании.
        /// </summary>
        public static string WithdrawalView_Pending {
            get {
                return ResourceManager.GetString("WithdrawalView_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данный момент идет обработка Вашего запроса на вывод средств..
        /// </summary>
        public static string WithdrawalView_Pending_Withdrawal_Text {
            get {
                return ResourceManager.GetString("WithdrawalView_Pending_Withdrawal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш запрос обрабатывается, время ожидания может составить до 24 часов.
        /// </summary>
        public static string WithdrawalView_Pendng_Verify_User_Text {
            get {
                return ResourceManager.GetString("WithdrawalView_Pendng_Verify_User_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозвать.
        /// </summary>
        public static string WithdrawalView_Revoke_Button {
            get {
                return ResourceManager.GetString("WithdrawalView_Revoke_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string WithdrawalView_Status_Text {
            get {
                return ResourceManager.GetString("WithdrawalView_Status_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string WithdrawalView_Surname {
            get {
                return ResourceManager.GetString("WithdrawalView_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того чтобы вывести средства со своего счета, Вам необходимо подтвердить свою личность прикрепив селфи с паспортом в развернутом виде..
        /// </summary>
        public static string WithdrawalView_Verify_User_Text {
            get {
                return ResourceManager.GetString("WithdrawalView_Verify_User_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отозвать.
        /// </summary>
        public static string WithdrawalView_Withdraw_Text {
            get {
                return ResourceManager.GetString("WithdrawalView_Withdraw_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г..
        /// </summary>
        public static string Year_Short {
            get {
                return ResourceManager.GetString("Year_Short", resourceCulture);
            }
        }
    }
}
