//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrankChat.Mobile.Core.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PrankChat.Mobile.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string PerDay {
            get {
                return ResourceManager.GetString("PerDay", resourceCulture);
            }
        }
        
        public static string PerWeek {
            get {
                return ResourceManager.GetString("PerWeek", resourceCulture);
            }
        }
        
        public static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        public static string PerQuarter {
            get {
                return ResourceManager.GetString("PerQuarter", resourceCulture);
            }
        }
        
        public static string PerHalfYear {
            get {
                return ResourceManager.GetString("PerHalfYear", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string ErrorUnexpectedServer {
            get {
                return ResourceManager.GetString("ErrorUnexpectedServer", resourceCulture);
            }
        }
        
        public static string ErrorUnexpectedNetwork {
            get {
                return ResourceManager.GetString("ErrorUnexpectedNetwork", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string StepTwo {
            get {
                return ResourceManager.GetString("StepTwo", resourceCulture);
            }
        }
        
        public static string StepThree {
            get {
                return ResourceManager.GetString("StepThree", resourceCulture);
            }
        }
        
        public static string GoToFeed {
            get {
                return ResourceManager.GetString("GoToFeed", resourceCulture);
            }
        }
        
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        public static string Replenish {
            get {
                return ResourceManager.GetString("Replenish", resourceCulture);
            }
        }
        
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        public static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        public static string NewOrders {
            get {
                return ResourceManager.GetString("NewOrders", resourceCulture);
            }
        }
        
        public static string OrderExecuted {
            get {
                return ResourceManager.GetString("OrderExecuted", resourceCulture);
            }
        }
        
        public static string AllOrdersInDispute {
            get {
                return ResourceManager.GetString("AllOrdersInDispute", resourceCulture);
            }
        }
        
        public static string MyOrdersInDispute {
            get {
                return ResourceManager.GetString("MyOrdersInDispute", resourceCulture);
            }
        }
        
        public static string NewDisputeOrders {
            get {
                return ResourceManager.GetString("NewDisputeOrders", resourceCulture);
            }
        }
        
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        public static string TakeAnOrder {
            get {
                return ResourceManager.GetString("TakeAnOrder", resourceCulture);
            }
        }
        
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        public static string UploadVideo {
            get {
                return ResourceManager.GetString("UploadVideo", resourceCulture);
            }
        }
        
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        public static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string ToAccept {
            get {
                return ResourceManager.GetString("ToAccept", resourceCulture);
            }
        }
        
        public static string InDispute {
            get {
                return ResourceManager.GetString("InDispute", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        public static string Cashbox {
            get {
                return ResourceManager.GetString("Cashbox", resourceCulture);
            }
        }
        
        public static string Replenishment {
            get {
                return ResourceManager.GetString("Replenishment", resourceCulture);
            }
        }
        
        public static string Withdrawal {
            get {
                return ResourceManager.GetString("Withdrawal", resourceCulture);
            }
        }
        
        public static string AvailableForRemoval {
            get {
                return ResourceManager.GetString("AvailableForRemoval", resourceCulture);
            }
        }
        
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        public static string Complain {
            get {
                return ResourceManager.GetString("Complain", resourceCulture);
            }
        }
        
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        public static string SubscribeToAuthor {
            get {
                return ResourceManager.GetString("SubscribeToAuthor", resourceCulture);
            }
        }
        
        public static string ShareLink {
            get {
                return ResourceManager.GetString("ShareLink", resourceCulture);
            }
        }
        
        public static string Moderation {
            get {
                return ResourceManager.GetString("Moderation", resourceCulture);
            }
        }
        
        public static string CanceledByModerator {
            get {
                return ResourceManager.GetString("CanceledByModerator", resourceCulture);
            }
        }
        
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string InWork {
            get {
                return ResourceManager.GetString("InWork", resourceCulture);
            }
        }
        
        public static string ClosingDispute {
            get {
                return ResourceManager.GetString("ClosingDispute", resourceCulture);
            }
        }
        
        public static string DisputeWon {
            get {
                return ResourceManager.GetString("DisputeWon", resourceCulture);
            }
        }
        
        public static string DisputeLost {
            get {
                return ResourceManager.GetString("DisputeLost", resourceCulture);
            }
        }
        
        public static string Accomplished {
            get {
                return ResourceManager.GetString("Accomplished", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        public static string TakeOrderQuestion {
            get {
                return ResourceManager.GetString("TakeOrderQuestion", resourceCulture);
            }
        }
        
        public static string SecondsShort {
            get {
                return ResourceManager.GetString("SecondsShort", resourceCulture);
            }
        }
        
        public static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        public static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
        
        public static string DaysShort {
            get {
                return ResourceManager.GetString("DaysShort", resourceCulture);
            }
        }
        
        public static string WeeksShort {
            get {
                return ResourceManager.GetString("WeeksShort", resourceCulture);
            }
        }
        
        public static string CountThousand {
            get {
                return ResourceManager.GetString("CountThousand", resourceCulture);
            }
        }
        
        public static string CountMillions {
            get {
                return ResourceManager.GetString("CountMillions", resourceCulture);
            }
        }
        
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        public static string OfViewing {
            get {
                return ResourceManager.GetString("OfViewing", resourceCulture);
            }
        }
        
        public static string YearShort {
            get {
                return ResourceManager.GetString("YearShort", resourceCulture);
            }
        }
        
        public static string WantToCancelOrder {
            get {
                return ResourceManager.GetString("WantToCancelOrder", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        public static string ProfileEditing {
            get {
                return ResourceManager.GetString("ProfileEditing", resourceCulture);
            }
        }
        
        public static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        public static string ChooseFromGallery {
            get {
                return ResourceManager.GetString("ChooseFromGallery", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string SelectValidityPeriod {
            get {
                return ResourceManager.GetString("SelectValidityPeriod", resourceCulture);
            }
        }
        
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PasswordRepeat {
            get {
                return ResourceManager.GetString("PasswordRepeat", resourceCulture);
            }
        }
        
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        public static string ValidationErrorGreaterThanRequired {
            get {
                return ResourceManager.GetString("ValidationErrorGreaterThanRequired", resourceCulture);
            }
        }
        
        public static string ValidationErrorLowerThanRequired {
            get {
                return ResourceManager.GetString("ValidationErrorLowerThanRequired", resourceCulture);
            }
        }
        
        public static string ValidationErrorNotMatch {
            get {
                return ResourceManager.GetString("ValidationErrorNotMatch", resourceCulture);
            }
        }
        
        public static string ValidationErrorCanNotMatch {
            get {
                return ResourceManager.GetString("ValidationErrorCanNotMatch", resourceCulture);
            }
        }
        
        public static string ValidationErrorInvalid {
            get {
                return ResourceManager.GetString("ValidationErrorInvalid", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        public static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }
        
        public static string Voting {
            get {
                return ResourceManager.GetString("Voting", resourceCulture);
            }
        }
        
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        public static string UntilEndVoting {
            get {
                return ResourceManager.GetString("UntilEndVoting", resourceCulture);
            }
        }
        
        public static string CompetitionPeriod {
            get {
                return ResourceManager.GetString("CompetitionPeriod", resourceCulture);
            }
        }
        
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        public static string Participate {
            get {
                return ResourceManager.GetString("Participate", resourceCulture);
            }
        }
        
        public static string TournamentPrizePool {
            get {
                return ResourceManager.GetString("TournamentPrizePool", resourceCulture);
            }
        }
        
        public static string BeforeStartVoting {
            get {
                return ResourceManager.GetString("BeforeStartVoting", resourceCulture);
            }
        }
        
        public static string CompetitionRules {
            get {
                return ResourceManager.GetString("CompetitionRules", resourceCulture);
            }
        }
        
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        public static string Contests {
            get {
                return ResourceManager.GetString("Contests", resourceCulture);
            }
        }
        
        public static string EmptyCardError {
            get {
                return ResourceManager.GetString("EmptyCardError", resourceCulture);
            }
        }
        
        public static string CancelWithdrawalError {
            get {
                return ResourceManager.GetString("CancelWithdrawalError", resourceCulture);
            }
        }
        
        public static string DeleteCard {
            get {
                return ResourceManager.GetString("DeleteCard", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteCardQuestion {
            get {
                return ResourceManager.GetString("DeleteCardQuestion", resourceCulture);
            }
        }
        
        public static string OnBoardingFirstTitle {
            get {
                return ResourceManager.GetString("OnBoardingFirstTitle", resourceCulture);
            }
        }
        
        public static string OnBoardingSecondTitle {
            get {
                return ResourceManager.GetString("OnBoardingSecondTitle", resourceCulture);
            }
        }
        
        public static string OnBoardingThirdTitle {
            get {
                return ResourceManager.GetString("OnBoardingThirdTitle", resourceCulture);
            }
        }
        
        public static string OnBoardingFourthTitle {
            get {
                return ResourceManager.GetString("OnBoardingFourthTitle", resourceCulture);
            }
        }
        
        public static string OnBoardingFifthTitle {
            get {
                return ResourceManager.GetString("OnBoardingFifthTitle", resourceCulture);
            }
        }
        
        public static string OnBoardingFirstDescription {
            get {
                return ResourceManager.GetString("OnBoardingFirstDescription", resourceCulture);
            }
        }
        
        public static string OnBoardingSecondDescription {
            get {
                return ResourceManager.GetString("OnBoardingSecondDescription", resourceCulture);
            }
        }
        
        public static string OnBoardingThirdDescription {
            get {
                return ResourceManager.GetString("OnBoardingThirdDescription", resourceCulture);
            }
        }
        
        public static string OnBoardingFourthDescription {
            get {
                return ResourceManager.GetString("OnBoardingFourthDescription", resourceCulture);
            }
        }
        
        public static string OnBoardingFifthDescription {
            get {
                return ResourceManager.GetString("OnBoardingFifthDescription", resourceCulture);
            }
        }
        
        public static string ThisIsSpam {
            get {
                return ResourceManager.GetString("ThisIsSpam", resourceCulture);
            }
        }
        
        public static string PornographyAndNudity {
            get {
                return ResourceManager.GetString("PornographyAndNudity", resourceCulture);
            }
        }
        
        public static string InsultingOrBullying {
            get {
                return ResourceManager.GetString("InsultingOrBullying", resourceCulture);
            }
        }
        
        public static string ViolenceOrDangerousOrganizations {
            get {
                return ResourceManager.GetString("ViolenceOrDangerousOrganizations", resourceCulture);
            }
        }
        
        public static string CopyrighInfringement {
            get {
                return ResourceManager.GetString("CopyrighInfringement", resourceCulture);
            }
        }
        
        public static string FraudOrDeception {
            get {
                return ResourceManager.GetString("FraudOrDeception", resourceCulture);
            }
        }
        
        public static string ThankYouForLettingUsKnow {
            get {
                return ResourceManager.GetString("ThankYouForLettingUsKnow", resourceCulture);
            }
        }
        
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        public static string UsesSomeoneElseName {
            get {
                return ResourceManager.GetString("UsesSomeoneElseName", resourceCulture);
            }
        }
        
        public static string InappropriateContent {
            get {
                return ResourceManager.GetString("InappropriateContent", resourceCulture);
            }
        }
        
        public static string InappropriateProfileInformation {
            get {
                return ResourceManager.GetString("InappropriateProfileInformation", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string OrderCreateMessage {
            get {
                return ResourceManager.GetString("OrderCreateMessage", resourceCulture);
            }
        }
        
        public static string ProcessingVideo {
            get {
                return ResourceManager.GetString("ProcessingVideo", resourceCulture);
            }
        }
        
        public static string ProfileYourEmailNotActual {
            get {
                return ResourceManager.GetString("ProfileYourEmailNotActual", resourceCulture);
            }
        }
        
        public static string ProfileEmailConfirmationSent {
            get {
                return ResourceManager.GetString("ProfileEmailConfirmationSent", resourceCulture);
            }
        }
        
        public static string TwentyFourHoursToPay {
            get {
                return ResourceManager.GetString("TwentyFourHoursToPay", resourceCulture);
            }
        }
        
        public static string NotVerified {
            get {
                return ResourceManager.GetString("NotVerified", resourceCulture);
            }
        }
        
        public static string WalkthrouthCompetitionsDescription {
            get {
                return ResourceManager.GetString("WalkthrouthCompetitionsDescription", resourceCulture);
            }
        }
        
        public static string WalkthrouthCreateOrderDescription {
            get {
                return ResourceManager.GetString("WalkthrouthCreateOrderDescription", resourceCulture);
            }
        }
        
        public static string WalkthrouthOrdersDescription {
            get {
                return ResourceManager.GetString("WalkthrouthOrdersDescription", resourceCulture);
            }
        }
        
        public static string WalkthrouthProfileDescription {
            get {
                return ResourceManager.GetString("WalkthrouthProfileDescription", resourceCulture);
            }
        }
        
        public static string CreateOrders {
            get {
                return ResourceManager.GetString("CreateOrders", resourceCulture);
            }
        }
        
        public static string OrderFeed {
            get {
                return ResourceManager.GetString("OrderFeed", resourceCulture);
            }
        }
        
        public static string NoIntentetConnection {
            get {
                return ResourceManager.GetString("NoIntentetConnection", resourceCulture);
            }
        }
        
        public static string VideoFailedToUpload {
            get {
                return ResourceManager.GetString("VideoFailedToUpload", resourceCulture);
            }
        }
        
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        public static string Kb {
            get {
                return ResourceManager.GetString("Kb", resourceCulture);
            }
        }
        
        public static string Mb {
            get {
                return ResourceManager.GetString("Mb", resourceCulture);
            }
        }
        
        public static string Gb {
            get {
                return ResourceManager.GetString("Gb", resourceCulture);
            }
        }
        
        public static string Tb {
            get {
                return ResourceManager.GetString("Tb", resourceCulture);
            }
        }
        
        public static string SubscriptionTemplate {
            get {
                return ResourceManager.GetString("SubscriptionTemplate", resourceCulture);
            }
        }
        
        public static string SubscribersTemplate {
            get {
                return ResourceManager.GetString("SubscribersTemplate", resourceCulture);
            }
        }
        
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        public static string SecretOrder {
            get {
                return ResourceManager.GetString("SecretOrder", resourceCulture);
            }
        }
        
        public static string WalkthrouthCreateOrderSecretDescription {
            get {
                return ResourceManager.GetString("WalkthrouthCreateOrderSecretDescription", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string PayForParticipation {
            get {
                return ResourceManager.GetString("PayForParticipation", resourceCulture);
            }
        }
        
        public static string CompetionRulesTemplate {
            get {
                return ResourceManager.GetString("CompetionRulesTemplate", resourceCulture);
            }
        }
        
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        public static string ErrorSomethingWentWrongMessage {
            get {
                return ResourceManager.GetString("ErrorSomethingWentWrongMessage", resourceCulture);
            }
        }
        
        public static string WithdrawalYoomoneyDescription {
            get {
                return ResourceManager.GetString("WithdrawalYoomoneyDescription", resourceCulture);
            }
        }
        
        public static string Yoomoney {
            get {
                return ResourceManager.GetString("Yoomoney", resourceCulture);
            }
        }
        
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        public static string BlockedUser {
            get {
                return ResourceManager.GetString("BlockedUser", resourceCulture);
            }
        }
        
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        public static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        public static string MyFeed {
            get {
                return ResourceManager.GetString("MyFeed", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        public static string CreateNewOneAccount {
            get {
                return ResourceManager.GetString("CreateNewOneAccount", resourceCulture);
            }
        }
        
        public static string EnterSocialNetworks {
            get {
                return ResourceManager.GetString("EnterSocialNetworks", resourceCulture);
            }
        }
        
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        public static string LoginIn {
            get {
                return ResourceManager.GetString("LoginIn", resourceCulture);
            }
        }
        
        public static string EnterNickname {
            get {
                return ResourceManager.GetString("EnterNickname", resourceCulture);
            }
        }
        
        public static string EnterYourName {
            get {
                return ResourceManager.GetString("EnterYourName", resourceCulture);
            }
        }
        
        public static string EnterBirthday {
            get {
                return ResourceManager.GetString("EnterBirthday", resourceCulture);
            }
        }
        
        public static string EnterPasswordAgain {
            get {
                return ResourceManager.GetString("EnterPasswordAgain", resourceCulture);
            }
        }
        
        public static string SelectSex {
            get {
                return ResourceManager.GetString("SelectSex", resourceCulture);
            }
        }
        
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        public static string PasswordRecoveryOnMail {
            get {
                return ResourceManager.GetString("PasswordRecoveryOnMail", resourceCulture);
            }
        }
        
        public static string FeaturedVideos {
            get {
                return ResourceManager.GetString("FeaturedVideos", resourceCulture);
            }
        }
        
        public static string CustomSubscriptions {
            get {
                return ResourceManager.GetString("CustomSubscriptions", resourceCulture);
            }
        }
        
        public static string Faq {
            get {
                return ResourceManager.GetString("Faq", resourceCulture);
            }
        }
        
        public static string ReferencesOrReviews {
            get {
                return ResourceManager.GetString("ReferencesOrReviews", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        public static string Performed {
            get {
                return ResourceManager.GetString("Performed", resourceCulture);
            }
        }
        
        public static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        public static string Ordered {
            get {
                return ResourceManager.GetString("Ordered", resourceCulture);
            }
        }
        
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        public static string OrderName {
            get {
                return ResourceManager.GetString("OrderName", resourceCulture);
            }
        }
        
        public static string OrderDescription {
            get {
                return ResourceManager.GetString("OrderDescription", resourceCulture);
            }
        }
        
        public static string TenThousand {
            get {
                return ResourceManager.GetString("TenThousand", resourceCulture);
            }
        }
        
        public static string DateOfExecution {
            get {
                return ResourceManager.GetString("DateOfExecution", resourceCulture);
            }
        }
        
        public static string HideArtist {
            get {
                return ResourceManager.GetString("HideArtist", resourceCulture);
            }
        }
        
        public static string OrderMatch {
            get {
                return ResourceManager.GetString("OrderMatch", resourceCulture);
            }
        }
        
        public static string MethodToReplenish {
            get {
                return ResourceManager.GetString("MethodToReplenish", resourceCulture);
            }
        }
        
        public static string TakeOff {
            get {
                return ResourceManager.GetString("TakeOff", resourceCulture);
            }
        }
        
        public static string SelectMethodToWithdrawal {
            get {
                return ResourceManager.GetString("SelectMethodToWithdrawal", resourceCulture);
            }
        }
        
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        public static string ShareThis {
            get {
                return ResourceManager.GetString("ShareThis", resourceCulture);
            }
        }
        
        public static string OnInstagram {
            get {
                return ResourceManager.GetString("OnInstagram", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string YourGender {
            get {
                return ResourceManager.GetString("YourGender", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        public static string ChangeProfilePhoto {
            get {
                return ResourceManager.GetString("ChangeProfilePhoto", resourceCulture);
            }
        }
        
        public static string Viewed {
            get {
                return ResourceManager.GetString("Viewed", resourceCulture);
            }
        }
        
        public static string NotViewed {
            get {
                return ResourceManager.GetString("NotViewed", resourceCulture);
            }
        }
        
        public static string LoginToAccount {
            get {
                return ResourceManager.GetString("LoginToAccount", resourceCulture);
            }
        }
        
        public static string ComVkSdkAppId {
            get {
                return ResourceManager.GetString("ComVkSdkAppId", resourceCulture);
            }
        }
        
        public static string SentToModerator {
            get {
                return ResourceManager.GetString("SentToModerator", resourceCulture);
            }
        }
        
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        public static string AttachFile {
            get {
                return ResourceManager.GetString("AttachFile", resourceCulture);
            }
        }
        
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        public static string PrizePool {
            get {
                return ResourceManager.GetString("PrizePool", resourceCulture);
            }
        }
        
        public static string PendingVerifyUser {
            get {
                return ResourceManager.GetString("PendingVerifyUser", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string PendingWithdrawal {
            get {
                return ResourceManager.GetString("PendingWithdrawal", resourceCulture);
            }
        }
        
        public static string DateOfCreation {
            get {
                return ResourceManager.GetString("DateOfCreation", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        public static string CommisionWarning {
            get {
                return ResourceManager.GetString("CommisionWarning", resourceCulture);
            }
        }
        
        public static string ConfirmAdult {
            get {
                return ResourceManager.GetString("ConfirmAdult", resourceCulture);
            }
        }
        
        public static string AgreeWith {
            get {
                return ResourceManager.GetString("AgreeWith", resourceCulture);
            }
        }
        
        public static string TermsAndRules {
            get {
                return ResourceManager.GetString("TermsAndRules", resourceCulture);
            }
        }
        
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        public static string Prize {
            get {
                return ResourceManager.GetString("Prize", resourceCulture);
            }
        }
        
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        public static string Peoples {
            get {
                return ResourceManager.GetString("Peoples", resourceCulture);
            }
        }
        
        public static string ApplicationNewVersionReady {
            get {
                return ResourceManager.GetString("ApplicationNewVersionReady", resourceCulture);
            }
        }
        
        public static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        public static string Passport {
            get {
                return ResourceManager.GetString("Passport", resourceCulture);
            }
        }
        
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        public static string EnterWalletNumber {
            get {
                return ResourceManager.GetString("EnterWalletNumber", resourceCulture);
            }
        }
        
        public static string CreateOrderPrivacyMessage {
            get {
                return ResourceManager.GetString("CreateOrderPrivacyMessage", resourceCulture);
            }
        }
        
        public static string CreateOrderPrivacyLink {
            get {
                return ResourceManager.GetString("CreateOrderPrivacyLink", resourceCulture);
            }
        }
        
        public static string Orderss {
            get {
                return ResourceManager.GetString("Orderss", resourceCulture);
            }
        }
        
        public static string CreatingOrder {
            get {
                return ResourceManager.GetString("CreatingOrder", resourceCulture);
            }
        }
        
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        public static string Revoke {
            get {
                return ResourceManager.GetString("Revoke", resourceCulture);
            }
        }
        
        public static string NeedToConfirmYourIdentity {
            get {
                return ResourceManager.GetString("NeedToConfirmYourIdentity", resourceCulture);
            }
        }
        
        public static string InTheDispute {
            get {
                return ResourceManager.GetString("InTheDispute", resourceCulture);
            }
        }
        
        public static string ConfirmAgeAndAgreeRules {
            get {
                return ResourceManager.GetString("ConfirmAgeAndAgreeRules", resourceCulture);
            }
        }
        
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        public static string LoginWithoutRegistration {
            get {
                return ResourceManager.GetString("LoginWithoutRegistration", resourceCulture);
            }
        }
        
        public static string CreateContest {
            get {
                return ResourceManager.GetString("CreateContest", resourceCulture);
            }
        }
        
        public static string ParticipationFee {
            get {
                return ResourceManager.GetString("ParticipationFee", resourceCulture);
            }
        }
        
        public static string PercentageContributionPrizePool {
            get {
                return ResourceManager.GetString("PercentageContributionPrizePool", resourceCulture);
            }
        }
        
        public static string SecretContest {
            get {
                return ResourceManager.GetString("SecretContest", resourceCulture);
            }
        }
        
        public static string CollectionBidsFrom {
            get {
                return ResourceManager.GetString("CollectionBidsFrom", resourceCulture);
            }
        }
        
        public static string CollectionBidsFor {
            get {
                return ResourceManager.GetString("CollectionBidsFor", resourceCulture);
            }
        }
        
        public static string VotingFrom {
            get {
                return ResourceManager.GetString("VotingFrom", resourceCulture);
            }
        }
        
        public static string VotingFor {
            get {
                return ResourceManager.GetString("VotingFor", resourceCulture);
            }
        }
        
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        public static string IncorrectEmailOrPasswordException {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPasswordException", resourceCulture);
            }
        }
        
        public static string PerYear {
            get {
                return ResourceManager.GetString("PerYear", resourceCulture);
            }
        }
        
        public static string AllTime {
            get {
                return ResourceManager.GetString("AllTime", resourceCulture);
            }
        }
        
        public static string YouAreNotConfirmedAdultAge {
            get {
                return ResourceManager.GetString("YouAreNotConfirmedAdultAge", resourceCulture);
            }
        }
        
        public static string YouAreNotConfirmedUserAgreement {
            get {
                return ResourceManager.GetString("YouAreNotConfirmedUserAgreement", resourceCulture);
            }
        }
        
        public static string VideoIsDownloadedTemplate {
            get {
                return ResourceManager.GetString("VideoIsDownloadedTemplate", resourceCulture);
            }
        }
        
        public static string PublicationListIsEmpty {
            get {
                return ResourceManager.GetString("PublicationListIsEmpty", resourceCulture);
            }
        }
        
        public static string CompetitionsListIsEmpty {
            get {
                return ResourceManager.GetString("CompetitionsListIsEmpty", resourceCulture);
            }
        }
        
        public static string OrdersListIsEmpty {
            get {
                return ResourceManager.GetString("OrdersListIsEmpty", resourceCulture);
            }
        }
        
        public static string NotificationsListIsEmpty {
            get {
                return ResourceManager.GetString("NotificationsListIsEmpty", resourceCulture);
            }
        }
        
        public static string SubscribersListIsEmpty {
            get {
                return ResourceManager.GetString("SubscribersListIsEmpty", resourceCulture);
            }
        }
        
        public static string SubscriptionsListIsEmpty {
            get {
                return ResourceManager.GetString("SubscriptionsListIsEmpty", resourceCulture);
            }
        }
        
        public static string CommentsListIsEmpty {
            get {
                return ResourceManager.GetString("CommentsListIsEmpty", resourceCulture);
            }
        }
        
        public static string PublicationsNotFound {
            get {
                return ResourceManager.GetString("PublicationsNotFound", resourceCulture);
            }
        }
        
        public static string PeoplesNotFound {
            get {
                return ResourceManager.GetString("PeoplesNotFound", resourceCulture);
            }
        }
        
        public static string OrdersNotFound {
            get {
                return ResourceManager.GetString("OrdersNotFound", resourceCulture);
            }
        }
        
        public static string VideoLimitOnUploading {
            get {
                return ResourceManager.GetString("VideoLimitOnUploading", resourceCulture);
            }
        }
        
        public static string WantToCancelCompetition {
            get {
                return ResourceManager.GetString("WantToCancelCompetition", resourceCulture);
            }
        }
        
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        public static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        public static string OfTheInstallment {
            get {
                return ResourceManager.GetString("OfTheInstallment", resourceCulture);
            }
        }
        
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
    }
}
