//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrankChat.Mobile.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrankChat.Mobile.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполненный.
        /// </summary>
        public static string Accomplished {
            get {
                return ResourceManager.GetString("Accomplished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все заказы.
        /// </summary>
        public static string AllOrders {
            get {
                return ResourceManager.GetString("AllOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все заказы в споре.
        /// </summary>
        public static string AllOrdersInDispute {
            get {
                return ResourceManager.GetString("AllOrdersInDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание!.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно для снятия с учётом комиссии платёжного шлюза (оператора):.
        /// </summary>
        public static string AvailableForRemoval {
            get {
                return ResourceManager.GetString("AvailableForRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь {0} заблокирован.
        /// </summary>
        public static string BlockedUser {
            get {
                return ResourceManager.GetString("BlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировать пользователя.
        /// </summary>
        public static string BlockUser {
            get {
                return ResourceManager.GetString("BlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на байт.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменен.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменен модератором.
        /// </summary>
        public static string CanceledByModerator {
            get {
                return ResourceManager.GetString("CanceledByModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удается отменить транзакцию для вывода средств.
        /// </summary>
        public static string CancelWithdrawalError {
            get {
                return ResourceManager.GetString("CancelWithdrawalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не может быть пустым..
        /// </summary>
        public static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Касса.
        /// </summary>
        public static string Cashbox {
            get {
                return ResourceManager.GetString("Cashbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать из галереи.
        /// </summary>
        public static string ChooseFromGallery {
            get {
                return ResourceManager.GetString("ChooseFromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие спора.
        /// </summary>
        public static string ClosingDispute {
            get {
                return ResourceManager.GetString("ClosingDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чтобы принять участие в конкурсе, Вам необходимо заплатить {0} ₽.
        /// </summary>
        public static string CompetionRulesTemplate {
            get {
                return ResourceManager.GetString("CompetionRulesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила конкурса.
        /// </summary>
        public static string CompetitionRules {
            get {
                return ResourceManager.GetString("CompetitionRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период проведения конкурса:.
        /// </summary>
        public static string CompetitionsFinishedTerm {
            get {
                return ResourceManager.GetString("CompetitionsFinishedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До начала голосования:.
        /// </summary>
        public static string CompetitionsNewTerm {
            get {
                return ResourceManager.GetString("CompetitionsNewTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До конца голосования:.
        /// </summary>
        public static string CompetitionsVotingTerm {
            get {
                return ResourceManager.GetString("CompetitionsVotingTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пожаловаться....
        /// </summary>
        public static string Complain {
            get {
                return ResourceManager.GetString("Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мошенничество или обман.
        /// </summary>
        public static string ComplaintCheating {
            get {
                return ResourceManager.GetString("ComplaintCheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спасибо, что сообщили нам об этом.
        /// </summary>
        public static string ComplaintCompleteMessage {
            get {
                return ResourceManager.GetString("ComplaintCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Насилие или опасные организации.
        /// </summary>
        public static string ComplaintDangerousOrganizations {
            get {
                return ResourceManager.GetString("ComplaintDangerousOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оскорбления или травля.
        /// </summary>
        public static string ComplaintHostileUtterances {
            get {
                return ResourceManager.GetString("ComplaintHostileUtterances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порнография и нагота.
        /// </summary>
        public static string ComplaintNakedContent {
            get {
                return ResourceManager.GetString("ComplaintNakedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее.
        /// </summary>
        public static string ComplaintOther {
            get {
                return ResourceManager.GetString("ComplaintOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарушение авторских прав.
        /// </summary>
        public static string ComplaintRightsViolation {
            get {
                return ResourceManager.GetString("ComplaintRightsViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это спам.
        /// </summary>
        public static string ComplaintSpam {
            get {
                return ResourceManager.GetString("ComplaintSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неприемлемый контент.
        /// </summary>
        public static string ComplaintUnacceptableContent {
            get {
                return ResourceManager.GetString("ComplaintUnacceptableContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неприемлемая информация в профиле.
        /// </summary>
        public static string ComplaintUnacceptableInformationInProfile {
            get {
                return ResourceManager.GetString("ComplaintUnacceptableInformationInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использует чужое имя.
        /// </summary>
        public static string ComplaintWrongName {
            get {
                return ResourceManager.GetString("ComplaintWrongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конкурсы.
        /// </summary>
        public static string Contests {
            get {
                return ResourceManager.GetString("Contests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать ссылку.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        public static string CountMillions {
            get {
                return ResourceManager.GetString("CountMillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на k.
        /// </summary>
        public static string CountThousand {
            get {
                return ResourceManager.GetString("CountThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание заказа.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание заказов.
        /// </summary>
        public static string CreateOrders {
            get {
                return ResourceManager.GetString("CreateOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ₽.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на День.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дней.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на д..
        /// </summary>
        public static string DaysShort {
            get {
                return ResourceManager.GetString("DaysShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить карту.
        /// </summary>
        public static string DeleteCard {
            get {
                return ResourceManager.GetString("DeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить данную карту?.
        /// </summary>
        public static string DeleteCardQuestion {
            get {
                return ResourceManager.GetString("DeleteCardQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спор проигран.
        /// </summary>
        public static string DisputeLost {
            get {
                return ResourceManager.GetString("DisputeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спор выигран.
        /// </summary>
        public static string DisputeWon {
            get {
                return ResourceManager.GetString("DisputeWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный эмейл уже зарегистрирован.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта не может быть пустой..
        /// </summary>
        public static string EmptyCardError {
            get {
                return ResourceManager.GetString("EmptyCardError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упс, что то пошло не так :(.
        /// </summary>
        public static string ErrorSomethingWentWrongMessage {
            get {
                return ResourceManager.GetString("ErrorSomethingWentWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неожиданная сетевая ошибка, попробуйте снова..
        /// </summary>
        public static string ErrorUnexpectedNetwork {
            get {
                return ResourceManager.GetString("ErrorUnexpectedNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Непредвиденная ошибка на сервере..
        /// </summary>
        public static string ErrorUnexpectedServer {
            get {
                return ResourceManager.GetString("ErrorUnexpectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исполнитель:.
        /// </summary>
        public static string Executor {
            get {
                return ResourceManager.GetString("Executor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ГБ.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти в ленту.
        /// </summary>
        public static string GoToFeed {
            get {
                return ResourceManager.GetString("GoToFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок.
        /// </summary>
        public static string Headline {
            get {
                return ResourceManager.GetString("Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часа.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часов.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ч..
        /// </summary>
        public static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В спор.
        /// </summary>
        public static string InDispute {
            get {
                return ResourceManager.GetString("InDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В работе.
        /// </summary>
        public static string InWork {
            get {
                return ResourceManager.GetString("InWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КБ.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ссылка скопирована.
        /// </summary>
        public static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на МБ.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минут.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минут.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мин..
        /// </summary>
        public static string MinutesShort {
            get {
                return ResourceManager.GetString("MinutesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На модерации.
        /// </summary>
        public static string Moderation {
            get {
                return ResourceManager.GetString("Moderation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои заказы.
        /// </summary>
        public static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои заказы в споре.
        /// </summary>
        public static string MyOrdersInDispute {
            get {
                return ResourceManager.GetString("MyOrdersInDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые заказы в споре.
        /// </summary>
        public static string NewDisputeOrders {
            get {
                return ResourceManager.GetString("NewDisputeOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новые заказы.
        /// </summary>
        public static string NewOrders {
            get {
                return ResourceManager.GetString("NewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернет соединение отсувствует.
        /// </summary>
        public static string NoIntentetConnection {
            get {
                return ResourceManager.GetString("NoIntentetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уведомления.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не подтверждено.
        /// </summary>
        public static string NotVerified {
            get {
                return ResourceManager.GetString("NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на просмотра.
        /// </summary>
        public static string OfViewing {
            get {
                return ResourceManager.GetString("OfViewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ок.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Публикуй свое видео и стань известным.
        /// </summary>
        public static string OnBoardingFifthDescription {
            get {
                return ResourceManager.GetString("OnBoardingFifthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Делай это смешно и под музыку!.
        /// </summary>
        public static string OnBoardingFifthTitle {
            get {
                return ResourceManager.GetString("OnBoardingFifthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторы PrankChat публикуют только эксклюзивные, самые смешные и безумные видео! Смотри и наслаждайся.
        /// </summary>
        public static string OnBoardingFirstDescription {
            get {
                return ResourceManager.GetString("OnBoardingFirstDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотри и наслаждайся.
        /// </summary>
        public static string OnBoardingFirstTitle {
            get {
                return ResourceManager.GetString("OnBoardingFirstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принимай участие в креативных конкурсах! Сними лучшее видео и выиграй достойный денежный приз! А мы не возьмём с тебя ни копейки.
        /// </summary>
        public static string OnBoardingFourthDescription {
            get {
                return ResourceManager.GetString("OnBoardingFourthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участвуй в бесплатных конкурсах.
        /// </summary>
        public static string OnBoardingFourthTitle {
            get {
                return ResourceManager.GetString("OnBoardingFourthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размещай задание, стоимость и срок исполнения, по которому другие пользователи снимут для тебя видео. Получи ролик своей мечты!.
        /// </summary>
        public static string OnBoardingSecondDescription {
            get {
                return ResourceManager.GetString("OnBoardingSecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создай свой первый заказ.
        /// </summary>
        public static string OnBoardingSecondTitle {
            get {
                return ResourceManager.GetString("OnBoardingSecondTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Монетизируй свою любовь к творчеству! Снимай ролики для других пользователей и зарабатывай на этом реальные деньги.
        /// </summary>
        public static string OnBoardingThirdDescription {
            get {
                return ResourceManager.GetString("OnBoardingThirdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарабатывай, выполняя заказы.
        /// </summary>
        public static string OnBoardingThirdTitle {
            get {
                return ResourceManager.GetString("OnBoardingThirdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите создать заказ?.
        /// </summary>
        public static string OrderCreateMessage {
            get {
                return ResourceManager.GetString("OrderCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказ в исполнении.
        /// </summary>
        public static string OrderExecuted {
            get {
                return ResourceManager.GetString("OrderExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лента заказов.
        /// </summary>
        public static string OrderFeed {
            get {
                return ResourceManager.GetString("OrderFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма заказа:.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заказы.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время заказа:.
        /// </summary>
        public static string OrderTime {
            get {
                return ResourceManager.GetString("OrderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять участие.
        /// </summary>
        public static string Participate {
            get {
                return ResourceManager.GetString("Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановление пароля.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повтор пароля.
        /// </summary>
        public static string PasswordReplay {
            get {
                return ResourceManager.GetString("PasswordReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить.
        /// </summary>
        public static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплатить участие.
        /// </summary>
        public static string PayForParticipation {
            get {
                return ResourceManager.GetString("PayForParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В ожидании.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За день.
        /// </summary>
        public static string PerDay {
            get {
                return ResourceManager.GetString("PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За полгода.
        /// </summary>
        public static string PerHalfYear {
            get {
                return ResourceManager.GetString("PerHalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За месяц.
        /// </summary>
        public static string PerMonth {
            get {
                return ResourceManager.GetString("PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За квартал.
        /// </summary>
        public static string PerQuarter {
            get {
                return ResourceManager.GetString("PerQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За неделю.
        /// </summary>
        public static string PerWeek {
            get {
                return ResourceManager.GetString("PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка займёт несколько минут.
        /// </summary>
        public static string ProcessingVideo {
            get {
                return ResourceManager.GetString("ProcessingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРОФИЛЬ.
        /// </summary>
        public static string ProfileEditing {
            get {
                return ResourceManager.GetString("ProfileEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На Вашу почту отправлено письмо с подтверждением.
        /// </summary>
        public static string ProfileEmailConfirmationSent {
            get {
                return ResourceManager.GetString("ProfileEmailConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша почта не подтверждена.
        /// </summary>
        public static string ProfileYourEmailNotActual {
            get {
                return ResourceManager.GetString("ProfileYourEmailNotActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пополнить.
        /// </summary>
        public static string Replenish {
            get {
                return ResourceManager.GetString("Replenish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пополнение.
        /// </summary>
        public static string Replenishment {
            get {
                return ResourceManager.GetString("Replenishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результаты.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сек..
        /// </summary>
        public static string SecondsShort {
            get {
                return ResourceManager.GetString("SecondsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секретный заказ.
        /// </summary>
        public static string SecretOrder {
            get {
                return ResourceManager.GetString("SecretOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите период действия заказа..
        /// </summary>
        public static string SelectValidityPeriod {
            get {
                return ResourceManager.GetString("SelectValidityPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поделиться.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поделиться ссылкой.
        /// </summary>
        public static string ShareLink {
            get {
                return ResourceManager.GetString("ShareLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти из аккаунта.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг 3.
        /// </summary>
        public static string StepThree {
            get {
                return ResourceManager.GetString("StepThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг 2.
        /// </summary>
        public static string StepTwo {
            get {
                return ResourceManager.GetString("StepTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписаться.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписчики {0}.
        /// </summary>
        public static string SubscribersTemplate {
            get {
                return ResourceManager.GetString("SubscribersTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписаться на автора.
        /// </summary>
        public static string SubscribeToAuthor {
            get {
                return ResourceManager.GetString("SubscribeToAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подписки {0}.
        /// </summary>
        public static string SubscriptionTemplate {
            get {
                return ResourceManager.GetString("SubscriptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итоги.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Взять заказ.
        /// </summary>
        public static string TakeAnOrder {
            get {
                return ResourceManager.GetString("TakeAnOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для принятия заказа необходимо внести задаток, как гарантию его выполнения:
        ///20% стоимости для обычных заказов
        ///40% для секретных заказов .
        /// </summary>
        public static string TakeOrderQuestion {
            get {
                return ResourceManager.GetString("TakeOrderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cфотографировать.
        /// </summary>
        public static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТБ.
        /// </summary>
        public static string TB {
            get {
                return ResourceManager.GetString("TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять.
        /// </summary>
        public static string ToAccept {
            get {
                return ResourceManager.GetString("ToAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Призовой фонд турнира:.
        /// </summary>
        public static string TournamentPrizePool {
            get {
                return ResourceManager.GetString("TournamentPrizePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У заказчика есть 24 часа на оплату.
        /// </summary>
        public static string TwentyFourHoursToPay {
            get {
                return ResourceManager.GetString("TwentyFourHoursToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отписаться.
        /// </summary>
        public static string Unsubscribe {
            get {
                return ResourceManager.GetString("Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить видео:.
        /// </summary>
        public static string UploadVideo {
            get {
                return ResourceManager.GetString("UploadVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не может быть равно {1}..
        /// </summary>
        public static string ValidationErrorCanNotMatch {
            get {
                return ResourceManager.GetString("ValidationErrorCanNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не может быть больше чем {1}..
        /// </summary>
        public static string ValidationErrorGreaterThanRequired {
            get {
                return ResourceManager.GetString("ValidationErrorGreaterThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} имеет неверный формат..
        /// </summary>
        public static string ValidationErrorInvalid {
            get {
                return ResourceManager.GetString("ValidationErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не может быть меньше чем {1}..
        /// </summary>
        public static string ValidationErrorLowerThanRequired {
            get {
                return ResourceManager.GetString("ValidationErrorLowerThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} не совпадает с {1}..
        /// </summary>
        public static string ValidationErrorNotMatch {
            get {
                return ResourceManager.GetString("ValidationErrorNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки видео.
        /// </summary>
        public static string VideoFailedToUpload {
            get {
                return ResourceManager.GetString("VideoFailedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на просмотр.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на просмотров.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосование.
        /// </summary>
        public static string Voting {
            get {
                return ResourceManager.GetString("Voting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Участвуй в конкурсах с денежными призами! Читай условия и скорее размещай своё видео. Победители будут выбраны путём общего голосования и моментально получат на свой счёт призовые деньги. Не забудь позвать своих друзей на голосование, они увеличат твои шансы на победу!
        ///
        ///Конкурс состоит из трех этапов:
        ///1) На начальном этапе участники отправляют на конкурс свои видеоролики;
        ///2) Голосование. Пользователи PrankChat отдают голоса за понравившееся видео;
        ///3) Итоги. После подведения итогов на счета участников, чьи в [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string WalkthrouthCompetitionsDescription {
            get {
                return ResourceManager.GetString("WalkthrouthCompetitionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размещай своё задание, по которому другие пользователи снимут для тебя видео. Описывай задачу как можно подробнее, устанавливай срок исполнения и сумму вознаграждения, чтобы получить идеальный ролик..
        /// </summary>
        public static string WalkthrouthCreateOrderDescription {
            get {
                return ResourceManager.GetString("WalkthrouthCreateOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст «Секретного заказа» не виден и появляется только при принятии заказа исполнителем. 
        ///Для принятия заказа необходимо внести 40% от его общей стоимости как гарантию выполнения заказа. 
        ///В случае невыполнения в отведенное время заказчик зарабатывает 20%, поэтому выгодно создавать труднорешаемые и интересные задачи. Задание может быть сложным, но обязательно выполнимым. 
        ///Если задание невыполнимо, исполнитель может загрузить видео, в котором укажет причину, по которой невозможно снять видео, а заказчик при н [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string WalkthrouthCreateOrderSecretDescription {
            get {
                return ResourceManager.GetString("WalkthrouthCreateOrderSecretDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты можешь взять любой заказ из категории «Новый» и загрузить готовое видео согласно заданию. Чтобы принять заказ, внеси 20% от его стоимости в качестве гарантии, что не забросишь его исполнение. Когда заказчик проверит твоё видео и одобрит его, жди оплату на свой счёт. Если же заказчик забыл одобрить заказ, деньги тебе поступят автоматически через 24 часа. 20 % от стоимости заказа составляет комиссия PrankChat.
        ///
        ///В случае, если заказчику не понравилось твоё видео, он может отправить задание в «спор». Там в т [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string WalkthrouthOrdersDescription {
            get {
                return ResourceManager.GetString("WalkthrouthOrdersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В профиле пользователь может отслеживать сумму денежных средств на расчетном счете, а также все свои задания: опубликованные, исполняемые и исполненные..
        /// </summary>
        public static string WalkthrouthProfileDescription {
            get {
                return ResourceManager.GetString("WalkthrouthProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите отменить заказ?.
        /// </summary>
        public static string WantToCancelOrder {
            get {
                return ResourceManager.GetString("WantToCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смотреть.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нед..
        /// </summary>
        public static string WeeksShort {
            get {
                return ResourceManager.GetString("WeeksShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снятие.
        /// </summary>
        public static string Withdrawal {
            get {
                return ResourceManager.GetString("Withdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывод средств осуществляется через кошелек ЮMoney (Яндекс кошелёк)..
        /// </summary>
        public static string WithdrawalYoomoneyDescription {
            get {
                return ResourceManager.GetString("WithdrawalYoomoneyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на г..
        /// </summary>
        public static string YearShort {
            get {
                return ResourceManager.GetString("YearShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЮMoney.
        /// </summary>
        public static string Yoomoney {
            get {
                return ResourceManager.GetString("Yoomoney", resourceCulture);
            }
        }
    }
}
